ALTER USER SCOTT IDENTIFIED BY tiger ACCOUNT UNLOCK

CREATE USER BOARDTEST IDENTIFIED BY BOARDTEST 
GRANT CONNECT, RESOURCE TO BOARDTEST 
ALTER USER BOARDTEST DEFAULT TABLESPACE USERS
ALTER USER BOARDTEST TEMPORARY TABLESPACE TEMP

SELECT FROM DBA_DATA_FILES
SELECT * FROM DBA_TABLESPACES
SELECT * FROM USER_USERS
