CREATE SEQUENCE SEQ INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE

CREATE TABLE EMAIL (
	EADRESS VARCHAR2(10) PRIMARY KEY,
	EPW VARCHAR2(10) NOT NULL, 
	PHONE VARCHAR2(11) NOT NULL,
	AUTHEN NUMBER(4) NOT NULL,
	ACTIVE VARCHAR2(10) NOT NULL
	)
INSERT INTO EMAIL (EADRESS, EPW, PHONE, AUTHEN, ACTIVE)
VALUES ('EADR1', 'EPW1', '01011111111', 1111, 'ACTIVE')
INSERT INTO EMAIL (EADRESS, EPW, PHONE, AUTHEN, ACTIVE)
VALUES ('EADR2', 'EPW2', '01022222222', 2222, 'REST')
INSERT INTO EMAIL (EADRESS, EPW, PHONE, AUTHEN, ACTIVE)
VALUES ('EADR3', 'EPW3', '01033333333', 3333, 'NONE')
INSERT INTO EMAIL (EADRESS, EPW, PHONE, AUTHEN, ACTIVE)
VALUES ('TEST', 'TEST', 'TEST', 0000, 'ACTIVE')
SELECT * FROM EMAIL


CREATE TABLE MEMBER (
	MNO NUMBER(10) PRIMARY KEY,
	ID VARCHAR2(10) NOT NULL,
	PW VARCHAR2(10) NOT NULL,
	NICK VARCHAR2(10) NOT NULL, --NICKNAME
	EADRESS VARCHAR2(10) REFERENCES EMAIL(EADRESS),
	REGIDATE DATE DEFAULT SYSDATE NOT NULL,
	ACTIVE VARCHAR2(10) NOT NULL,
	CTG VARCHAR2(5) NOT NULL --CATEGORY
)
INSERT INTO MEMBER (MNO, ID, PW, NICK, EADRESS, ACTIVE, CTG)
VALUES (SEQ.NEXTVAL, 'ID1', 'PW1', 'NICK1', 'EADR1', 'ACTIVE', 'USER')
INSERT INTO MEMBER (MNO, ID, PW, NICK, EADRESS, ACTIVE, CTG)
VALUES (SEQ.NEXTVAL, 'ID2', 'PW2', 'NICK2', 'EADR1', 'REST', 'USER')
INSERT INTO MEMBER (MNO, ID, PW, NICK, EADRESS, ACTIVE, CTG)
VALUES (SEQ.NEXTVAL, 'ID3', 'PW3', 'NICK3', 'EADR2', 'ACTIVE', 'USER')
INSERT INTO MEMBER (MNO, ID, PW, NICK, EADRESS, ACTIVE, CTG)
VALUES (SEQ.NEXTVAL, 'ID4', 'PW4', 'NICK4', 'EADR3', 'ACTIVE', 'ADMIN')
SELECT * FROM MEMBER

DELETE FROM EMAIL
DELETE FROM MEMBER
DROP TABLE EMAIL
DROP TABLE MEMBER




